$ErrorActionPreference = "Stop"
$root = "D:\Python-project\travel_system"

$dirs = @(
    "frontend\public",
    "frontend\src\router",
    "frontend\src\store",
    "frontend\src\api",
    "frontend\src\views",
    "frontend\src\components",
    "frontend\src\assets\styles",
    "frontend\src\assets\images",
    "frontend\src\utils",
    "backend\app\api\v1",
    "backend\app\core\security",
    "backend\app\core\cache",
    "backend\app\agents\graph",
    "backend\app\tools",
    "backend\app\rag",
    "backend\app\llm",
    "backend\app\tasks",
    "backend\app\db\models",
    "backend\app\schemas",
    "backend\app\services",
    "backend\alembic",
    "backend\scripts",
    "backend\tests\unit",
    "backend\tests\integration",
    "backend\tests\functional",
    "backend\performance",
    "deploy\nginx",
    "deploy\env",
    "docs"
)

foreach ($d in $dirs) {
    $p = Join-Path $root $d
    if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null }
}

$files = @(
    "frontend\public\favicon.ico",
    "frontend\src\main.js",
    "frontend\src\App.vue",
    "frontend\src\router\index.js",
    "frontend\src\store\index.js",
    "frontend\src\store\user.js",
    "frontend\src\store\travel.js",
    "frontend\src\api\request.js",
    "frontend\src\api\auth.js",
    "frontend\src\api\travel.js",
    "frontend\src\api\chat.js",
    "frontend\src\api\knowledge.js",
    "frontend\src\views\Login.vue",
    "frontend\src\views\TravelCreate.vue",
    "frontend\src\views\TravelList.vue",
    "frontend\src\views\TravelDetail.vue",
    "frontend\src\views\ChatAssistant.vue",
    "frontend\src\components\MapView.vue",
    "frontend\src\components\TravelCard.vue",
    "frontend\src\components\ChatBox.vue",
    "frontend\src\components\BudgetPanel.vue",
    "frontend\src\components\WeatherTag.vue",
    "frontend\src\utils\format.js",
    "frontend\index.html",
    "frontend\vite.config.js",
    "frontend\.env.example",
    "frontend\package.json",
    "frontend\Dockerfile",
    "backend\app\__init__.py",
    "backend\app\main.py",
    "backend\app\api\__init__.py",
    "backend\app\api\deps.py",
    "backend\app\api\v1\__init__.py",
    "backend\app\api\v1\auth.py",
    "backend\app\api\v1\travel.py",
    "backend\app\api\v1\chat.py",
    "backend\app\api\v1\knowledge.py",
    "backend\app\core\__init__.py",
    "backend\app\core\config.py",
    "backend\app\core\logging.py",
    "backend\app\core\security\__init__.py",
    "backend\app\core\security\jwt.py",
    "backend\app\core\security\password.py",
    "backend\app\core\cache\__init__.py",
    "backend\app\core\cache\redis_client.py",
    "backend\app\core\exceptions.py",
    "backend\app\agents\__init__.py",
    "backend\app\agents\master_agent.py",
    "backend\app\agents\route_agent.py",
    "backend\app\agents\review_agent.py",
    "backend\app\agents\graph\__init__.py",
    "backend\app\agents\graph\state.py",
    "backend\app\agents\graph\builder.py",
    "backend\app\tools\__init__.py",
    "backend\app\tools\weather_tool.py",
    "backend\app\tools\map_poi_tool.py",
    "backend\app\tools\budget_tool.py",
    "backend\app\tools\web_search_tool.py",
    "backend\app\rag\__init__.py",
    "backend\app\rag\embedding.py",
    "backend\app\rag\text_splitter.py",
    "backend\app\rag\vector_store.py",
    "backend\app\rag\retriever.py",
    "backend\app\rag\reranker.py",
    "backend\app\rag\knowledge_loader.py",
    "backend\app\llm\__init__.py",
    "backend\app\llm\dify_client.py",
    "backend\app\tasks\__init__.py",
    "backend\app\tasks\celery_app.py",
    "backend\app\tasks\travel_tasks.py",
    "backend\app\db\__init__.py",
    "backend\app\db\base.py",
    "backend\app\db\session.py",
    "backend\app\db\models\__init__.py",
    "backend\app\db\models\user.py",
    "backend\app\db\models\travel_task.py",
    "backend\app\db\models\travel_plan.py",
    "backend\app\db\models\chat_record.py",
    "backend\app\db\models\knowledge_base.py",
    "backend\app\schemas\__init__.py",
    "backend\app\schemas\user_schema.py",
    "backend\app\schemas\travel_schema.py",
    "backend\app\schemas\chat_schema.py",
    "backend\app\schemas\knowledge_schema.py",
    "backend\app\schemas\common.py",
    "backend\app\services\__init__.py",
    "backend\app\services\user_service.py",
    "backend\app\services\travel_service.py",
    "backend\app\services\chat_service.py",
    "backend\app\services\knowledge_service.py",
    "backend\scripts\seed_knowledge.py",
    "backend\tests\__init__.py",
    "backend\performance\travel_plan_test.jmx",
    "backend\alembic.ini",
    "backend\.env.example",
    "backend\requirements.txt",
    "backend\Dockerfile",
    "deploy\docker-compose.yml",
    "deploy\nginx\nginx.conf",
    "deploy\env\backend.env",
    "deploy\env\mysql.env",
    "deploy\env\redis.env",
    "docs\api-doc.md",
    "docs\architecture.md",
    "docs\deploy-guide.md",
    ".gitignore",
    "README.md",
    "LICENSE"
)

foreach ($f in $files) {
    $p = Join-Path $root $f
    $parent = Split-Path $p -Parent
    if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    if (-not (Test-Path $p)) { New-Item -ItemType File -Path $p -Force | Out-Null }
}

$emptyDirs = @(
    "frontend\src\assets\styles",
    "frontend\src\assets\images",
    "backend\alembic",
    "backend\tests\unit",
    "backend\tests\integration",
    "backend\tests\functional"
)
foreach ($d in $emptyDirs) {
    $p = Join-Path (Join-Path $root $d) ".gitkeep"
    if (-not (Test-Path $p)) { New-Item -ItemType File -Path $p -Force | Out-Null }
}

Write-Host "SCAFFOLD_DONE"
